better repo workflow

diff --git a/.github/workflows/repos.yml b/.github/workflows/repos.yml
--- a/.github/workflows/repos.yml
+++ b/.github/workflows/repos.yml
@@ -19,6 +19,7 @@ concurrency:
 
 jobs:
   check_repo:
+    if: github.ref == 'refs/heads/main' && vars.REPO_WORKFLOW_DISABLED != 'true'
     runs-on: ubuntu-latest
     outputs:
       is_main_repo: ${{ steps.check.outputs.is_main_repo }}
@@ -33,6 +34,7 @@ jobs:
           echo "Repository: $GITHUB_REPOSITORY"
 
   generate-matrix:
+    if: github.ref == 'refs/heads/main' && needs.check_repo.outputs.is_main_repo == 'false' && vars.REPO_WORKFLOW_DISABLED != 'true'
     runs-on: ubuntu-latest
     outputs:
       matrix: ${{ steps.set-matrix.outputs.matrix }}
@@ -50,7 +52,7 @@ jobs:
     needs:
       - check_repo
       - generate-matrix
-    if: github.ref == 'refs/heads/main' && needs.check_repo.outputs.is_main_repo == 'false'
+    if: github.ref == 'refs/heads/main' && needs.check_repo.outputs.is_main_repo == 'false' && vars.REPO_WORKFLOW_DISABLED != 'true'
     runs-on: ${{ matrix.host }}
     strategy:
       matrix: 
@@ -63,7 +65,14 @@ jobs:
 
       - name: Install GPG Key
         run: |
-          echo "${{ secrets.GPG_SIGNING_KEY }}" | gpg --import
+          if [[ -n "${{ secrets.GPG_SIGNING_KEY }}" ]]; then
+            echo "${{ secrets.GPG_SIGNING_KEY }}" | gpg --import
+          else
+            echo "Error: GPG_SIGNING_KEY is not set"
+            echo "please set it in the repository settings"
+            echo "(Secrets & variables -> Actions -> New Repository Secret)"
+            exit 1
+          fi
 
       - name: Install Dependencies
         run: |
@@ -93,7 +102,7 @@ jobs:
 
   deploy:
     needs: build
-    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
+    if: github.ref == 'refs/heads/main' && needs.check_repo.outputs.is_main_repo == 'false' && vars.REPO_WORKFLOW_DISABLED != 'true'
     environment:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
